[package]
name = "rust-ml-api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tract-onnx = "0.22.0"
tract-core = "0.22.0"
env_logger = "0.11"
log = "0.4"
